name: pull-request
on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fleet test
      uses: StrongMonkey/flt-test@v0.0.1