name: pull-request
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: download fleet manager cli
      run: |-
        mkdir -p bin
        curl -sfL https://github.com/StrongMonkey/fleet/releases/download/v0.0.0.-test/flt > ./bin/flt && chmod +x ./bin/flt
    - name: Run fleet test
      run: |
        ./bin/flt test