name: push
on:
  push:
    branches: [ master ]

jobs:
  apply:
    env:
      KUBECONFIG: ${{ secrets.kubeconfig }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fleet apply
      uses: StrongMonkey/flt-apply@v0.0.1
